jobs:
  action:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Fetch Tools
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Tests
        run: ./build/test

name: Workflow

on:
  schedule:
    - cron: "45 0/3 * * *"
